theme: minima
title: Vincent Kowalski's homepage
description: CFD doctorant - Supercritical flows - Heat transfers
header_pages:
  - about.md
  - cv.md
  - projects.md
  - blog_articles.md
  - publications.md
  - contact.md
